"""Change description field to TEXT in items table

Revision ID: 4c8cfa7640fa
Revises: a6df11e2692c
Create Date: 2025-08-23 10:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8cfa7640fa'
down_revision: Union[str, None] = '74ae5c0a38b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Изменяем поле description с VARCHAR(500) на TEXT
    op.alter_column('items', 'description',
                    existing_type=sa.String(length=500),
                    type_=sa.Text(),
                    existing_nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Возвращаем поле description обратно к VARCHAR(500)
    op.alter_column('items', 'description',
                    existing_type=sa.Text(),
                    type_=sa.String(length=500),
                    existing_nullable=False)
    
    # ### end Alembic commands ###
