"""Add item_image column to items table

Revision ID: 74ae5c0a38b9
Revises: 78bdfed4addd
Create Date: 2025-08-23 10:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ae5c0a38b9'
down_revision: Union[str, None] = '78bdfed4addd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем поле item_image в таблицу items
    op.add_column('items', sa.Column('item_image', sa.String(length=255), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем поле item_image из таблицы items
    op.drop_column('items', 'item_image')
    
    # ### end Alembic commands ###
