"""Create database schema to match models

Revision ID: 78bdfed4addd
Revises: 
Create Date: 2025-08-23 09:47:31.973055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bdfed4addd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('START', 'JAIL', 'AUCTION', 'LOTTERY', 'GAME', 'TRAP', 'QUESTION', name='celltype'), nullable=False),
    sa.Column('background_image', sa.String(length=255), nullable=False),
    sa.Column('main_conditions', sa.Text(), nullable=False),
    sa.Column('genre_conditions', sa.Text(), nullable=True),
    sa.Column('traps', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('BUFF', 'DEBUFF', 'TRAP', 'NEUTRAL', name='itemtype'), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.Column('modifier_turns', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('item_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('modifier_turns', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_instances_inventory_id'), 'item_instances', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_item_instances_item_id'), 'item_instances', ['item_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('UNDEFINED', 'ADMIN', 'MODERATOR', 'PLAYER', name='userrights'), nullable=False),
    sa.Column('last_dice_value', sa.Integer(), nullable=False),
    sa.Column('previous_cell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_players_cell_id'), 'players', ['cell_id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    op.create_table('sessionusers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessionusers_session_id'), 'sessionusers', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessionusers_user_id'), 'sessionusers', ['user_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('condition_type', sa.Enum('MAIN', 'GENRE', name='gameconditions'), nullable=False),
    sa.Column('status', sa.Enum('PROGRESS', 'DROP', 'REROLLED', 'COMPLETED', name='gamestatus'), nullable=False),
    sa.Column('hours_played', sa.Float(), nullable=True),
    sa.Column('review_text', sa.String(length=1000), nullable=True),
    sa.Column('win_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_cell_id'), 'games', ['cell_id'], unique=False)
    op.create_index(op.f('ix_games_player_id'), 'games', ['player_id'], unique=False)
    op.create_table('playereffectss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('item_instance_id', sa.Integer(), nullable=True),
    sa.Column('effect_name', sa.String(length=100), nullable=False),
    sa.Column('effect_type', sa.Enum('PASSIVE', 'ACTIVE', 'TARGET', 'INSTANT', 'TRAP', name='effecttype'), nullable=False),
    sa.Column('effect_category', sa.Enum('DICE_MODIFIER', 'GAME_DIFFICULTY', 'MOVEMENT', 'TIME_MODIFIER', 'POINTS_MODIFIER', 'INVENTORY_MODIFIER', 'PROTECTION', 'TRAP', 'SPECIAL', name='effectcategory'), nullable=False),
    sa.Column('turns_remaining', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effect_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['item_instance_id'], ['item_instances.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playereffectss_item_instance_id'), 'playereffectss', ['item_instance_id'], unique=False)
    op.create_index(op.f('ix_playereffectss_player_id'), 'playereffectss', ['player_id'], unique=False)
    op.create_table('playerstatss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('win_points', sa.Integer(), nullable=False),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('count_completed_games', sa.Integer(), nullable=False),
    sa.Column('count_rerolled_games', sa.Integer(), nullable=False),
    sa.Column('count_dropped_games', sa.Integer(), nullable=False),
    sa.Column('count_used_items', sa.Integer(), nullable=False),
    sa.Column('average_dice_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstatss_player_id'), 'playerstatss', ['player_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerstatss_player_id'), table_name='playerstatss')
    op.drop_table('playerstatss')
    op.drop_index(op.f('ix_playereffectss_player_id'), table_name='playereffectss')
    op.drop_index(op.f('ix_playereffectss_item_instance_id'), table_name='playereffectss')
    op.drop_table('playereffectss')
    op.drop_index(op.f('ix_games_player_id'), table_name='games')
    op.drop_index(op.f('ix_games_cell_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_sessionusers_user_id'), table_name='sessionusers')
    op.drop_index(op.f('ix_sessionusers_session_id'), table_name='sessionusers')
    op.drop_table('sessionusers')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_cell_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_item_instances_item_id'), table_name='item_instances')
    op.drop_index(op.f('ix_item_instances_inventory_id'), table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_table('users')
    op.drop_table('sessions')
    op.drop_table('items')
    op.drop_table('inventories')
    op.drop_table('cells')
    # ### end Alembic commands ###
