"""Populate items table with game items data

Revision ID: b1358dbfd957
Revises: bd7196417521
Create Date: 2025-08-23 10:36:11.686181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1358dbfd957'
down_revision: Union[str, None] = '4c8cfa7640fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Данные для предметов из ITEMS.md
    items_data = [
        {
            'title': 'Читерский кубик',
            'description': 'После броска кубиков заменяет значение на одном из них на то, которое выберет стример. За один ход можно использовать только 1 заряд. Если в инвентаре оказываются читерский кубик и кубик хуюбика, они уничтожают друг друга.',
            'item_image': 'public/storage/items/die.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Кубик хуюбика',
            'description': 'После следующего броска кубиков выберите тот, чье значение больше и поменяйте его на 1. Если в инвентаре оказываются читерский кубик и кубик хуюбика, они уничтожают друг друга.',
            'item_image': 'public/storage/items/die.png',
            'type': 'DEBUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Очки EZ',
            'description': 'Следующие два хода, не считая текущий, игры проходятся на самом легком уровне сложности. Игрок может начать текущую игру заново и выбрать легкий уровень сложности или поменять сложность в настройках посреди игры, если есть такая опция. Если в инвентаре оказываются очки EZ и повязка Рэмбо, они уничтожают друг друга.',
            'item_image': 'public/storage/items/ez.png',
            'type': 'BUFF',
            'uses': None,
            'modifier_turns': 2
        },
        {
            'title': 'Повязка Рэмбо',
            'description': 'Следующие два хода, не считая текущий, игры проходятся на самом высоком уровне сложности. Если в инвентаре оказываются очки EZ и повязка Рэмбо, они уничтожают друг друга.',
            'item_image': 'public/storage/items/rembo.png',
            'type': 'DEBUFF',
            'uses': None,
            'modifier_turns': 2
        },
        {
            'title': 'Свиток реролла',
            'description': 'При использовании произведите реролл игры. Использование свитка позволяет избавиться от эффектов, влияющий на ролл колеса (увеличение/уменьшение диапазона часов и т.д.) по желанию игрока.',
            'item_image': 'public/storage/items/scroll-reroll.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Шар всезнания',
            'description': 'При использовании можете воспользоваться гайдом, видеопрохождением или спидраном игры.',
            'item_image': 'public/storage/items/help.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Взрывчатка',
            'description': 'При попытке использования положительных свойств предметов, бросьте монетку. Сторону выбирайте сами. Одна сторона - эффект срабатывает, другая - эффект не срабатывает. Заряд при этом у предмета тратится в любом случае.',
            'item_image': 'public/storage/items/bomb.png',
            'type': 'DEBUFF',
            'uses': 2,
            'modifier_turns': None
        },
        {
            'title': 'Корона колесного короля',
            'description': 'После прокрута колеса, можете использовать корону, чтобы выбрать между двумя соседними играми. Не работает на клетке "Аукошная" и "Лотерея".',
            'item_image': 'public/storage/items/crown.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Ремонтный набор',
            'description': 'Увеличьте количество зарядов у любого вашего предмета на 1. Не работает на "Шоколад".',
            'item_image': 'public/storage/items/fix-stuff.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Красочная манга',
            'description': 'Позволяет проходить визуальную новеллу, но запрещен автоскип сцен. (Рука ОБЯЗАНА заебываться)',
            'item_image': 'public/storage/items/manga.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Рука мидаса',
            'description': 'При каждом ролле колеса приколов тратится заряд. Позволяет обменять выпавший на колесе приколов предмет на 2 победных очка',
            'item_image': 'public/storage/items/hand.png',
            'type': 'NEUTRAL',
            'uses': 2,
            'modifier_turns': None
        },
        {
            'title': 'Реверсивные сапоги',
            'description': 'Во время следующего хода бросьте один кубик вместо двух. Вернитесь назад на выпавшее значение кубика. На бросок не влияют никакие дополнительные эффекты. Не может повторно выпасть в ход, когда вы уже отступили назад благодаря данному предмету.',
            'item_image': 'public/storage/items/reverse-boots.png',
            'type': 'DEBUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Парные кольца времени',
            'description': 'Выберите другого игрока, у которого нет данного предмета. Теперь вы оба окольцованы. При использовании кольца тратят заряд и уменьшают верхнее и нижнее значение времени на клетке у того игрока, который использовал заряд, на 2 часа (но не меньше 1 часа и разница между верхним/нижним значением должна быть не меньше 1 часа). Количество зарядов общее для обоих стримеров. Если один из стримеров потеряет кольцо, второй также его потеряет. На одной клетке можно использовать только 1 заряд.',
            'item_image': 'public/storage/items/rings-of-time.png',
            'type': 'BUFF',
            'uses': 4,
            'modifier_turns': None
        },
        {
            'title': 'Тухлая шаурма',
            'description': 'Используйте на другого игрока, у которого нет данного предмета. У вашего конкурента несварение. Следующие два хода при передвижении он отнимает от каждого значения кубика 1. Значение на кубике не может быть меньше 1.',
            'item_image': 'public/storage/items/shawarma.png',
            'type': 'TRAP',
            'uses': 2,
            'modifier_turns': 2
        },
        {
            'title': 'Четырехлистный клевер',
            'description': 'Предмет имеет два свойства: 1) Можете потратить заряд и отбить любую ловушку. 2) На секторах "Аукошная" и "Лотерея" можете потратить заряд и договориться с главным судьей на +2 поинта за прохождение игры или пройти игру на легком уровне сложности.',
            'item_image': 'public/storage/items/clover.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Чокер боли',
            'description': 'Используйте на другого игрока, у которого нет данного предмета. Во время следующего прохождения игры на обычной клетке, он может проходить игру только по особым, жанровым правилам. Количество поинтов за прохождение игры все также х2 от базового.',
            'item_image': 'public/storage/items/choker.png',
            'type': 'TRAP',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Полукаловая монетка',
            'description': 'Используйте на другого игрока, у которого нет данного предмета. На следующей клетке с временным условием он подбрасывает монетку, где 1 сторона - -2 часа к верхнему\\нижнему порогу (но не меньше 1 часа и разница между верхним/нижним значением должна быть не меньше 1 часа), вторая - +3 часа.',
            'item_image': 'public/storage/items/halfshit-coin.png',
            'type': 'TRAP',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Шоколад',
            'description': 'При использовании уменьшает верхнее и нижнее значение времени на клетке на 1 час (но не меньше 1 часа и разница между верхним/нижним значением должна быть не меньше 1 часа). Шоколад можно копить. Когда скапливается 4 заряда, шоколад превращается в плитку (1 заряд). Любое временное значение на секторе становится 1-4 часов. Пока шоколад не стал плиткой, нельзя использовать больше одного заряда на одну клетку. Заряды увеличиваются только от другого шоколада (ремонтный набор не работает).',
            'item_image': 'public/storage/items/choco.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Туалетка',
            'description': 'Вы знатно обкекались. При дропе можете использовать заряд. Вместо перемещения на клетку "Тюрьма", вернитесь на клетку, на которой вы были на прошлом ходу. Если там нужно проходить игру, придется это сделать (за поинты, естественно). Не может заблокировать эффект от Дырявого парашюта.',
            'item_image': 'public/storage/items/toilet-paper.png',
            'type': 'BUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Штрафная квитанция',
            'description': 'На следующей клетке с временем, повысьте верхний и нижний порог на 3 часа. Можно использовать другие предметы и эффекты, чтобы невелировать свойства этого предмета.',
            'item_image': 'public/storage/items/fine-fuck....png',
            'type': 'DEBUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Дырявый парашют',
            'description': 'При дропе переместитесь на клетку "Старт" и потеряйте 2 поинта. Первая пройденная игра после дропа не принесет поинтов. Нельзя заблокироавть действие парашюта Туалеткой.',
            'item_image': 'public/storage/items/paraschute.png',
            'type': 'DEBUFF',
            'uses': 1,
            'modifier_turns': None
        },
        {
            'title': 'Наперсток удачи',
            'description': 'При каждом кручении колеса приколов замените один неугодный вам пункт на тот, который вам нужен. Озвучивать замену нужно перед каждым роллом. Если колесо уже крутится, а стример не озвучил замену, то сделать это уже нельзя.',
            'item_image': 'public/storage/items/lucky-on-a-finger.png',
            'type': 'BUFF',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Рука для fisting',
            'description': 'Используйте на другого игрока, у которого нет данного предмета. Теперь он ваш slave. Начиная с этого момента, каждый пятый заработанный point (за прохождение игры/кайфарик) он отдает вам и тратит заряд. Отдав суммарно 5 points, вы будете so fucking deep, что больше ничего получить от него не сможете. Если ваш slave получит из колеса руку для fisting, он сможет сделать slave вас, а ваша рука пропадет из его assventory. Если вы Dungeon master хотя бы у одного игрока, другие не могут быть вашим slave (реролл колеса). Нельзя fisting одного и того же игрока 2 раза подряд. Можно быть одновременно и slave и dungeon master.',
            'item_image': 'public/storage/items/fisting.png',
            'type': 'TRAP',
            'uses': 5,
            'modifier_turns': None
        },
        {
            'title': 'Тотем мошны',
            'description': 'Защищает игрока на текущий и следующий ход от ловушек-событий. Ловушки-предметы все также можно бросать в игрока под тотемом.',
            'item_image': 'public/storage/items/totem.png',
            'type': 'BUFF',
            'uses': None,
            'modifier_turns': 2
        },
        {
            'title': 'Плюсовый блокнот',
            'description': 'Если при броске двух кубиков на движение значение обоих одинаковое, то получите +2 к итоговому значению броска. Если выпадает две 6, то вместо + к движению, получите +1 поинт.',
            'item_image': 'public/storage/items/notebook.png',
            'type': 'BUFF',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Мистер Ржавчик',
            'description': 'Съедает у выбранного игрока случайный предмет-бафф.',
            'item_image': 'public/storage/items/rzhavchik.png',
            'type': 'TRAP',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Всепоглощающий свин',
            'description': 'Съедает у выбранного игрока случайный предмет-бафф.',
            'item_image': 'public/storage/items/pig.png',
            'type': 'TRAP',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Грабли',
            'description': 'Выбранный стример получает -1 к своему следующему броску кубиков на передвижение. Значение броска не может быть меньше 2.',
            'item_image': 'public/storage/items/grabli.png',
            'type': 'TRAP',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Липкая жижа',
            'description': 'Выбранный стример получает -1 к своему следующему броску кубика на передвижение. На секторе, с которого он совершает ход под действием жижы он оставляет след. Следующий наступивший на этот сектор стример получает -2 к своему следующему броску кубика на передвижения, после чего жижа пропадает. Значение броска не может быть меньше 2. Игрок оставляет лишь 1 след, сколько бы жиж на нем не было.',
            'item_image': 'public/storage/items/zhizha.png',
            'type': 'TRAP',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Тормознутый',
            'description': 'У выбранного игрока на следующей клетке с временным условием увеличивается нижний\\верхний порог на 1 час. Нельзя использовать на игрока, на котором уже есть два эффекта тормознутого.',
            'item_image': 'public/storage/items/toropiga.png',
            'type': 'TRAP',
            'uses': None,
            'modifier_turns': None
        },
        {
            'title': 'Крыса',
            'description': 'Выбранный стример получает -3 к своему следующему броску кубика на передвижение, а вы -1. Можно отказаться и зарероллить колесо. Значение броска не может быть меньше 2.',
            'item_image': 'public/storage/items/rat.png',
            'type': 'TRAP',
            'uses': None,
            'modifier_turns': None
        }
    ]
    
    # Вставляем данные в таблицу items
    for item_data in items_data:
        # Экранируем одинарные кавычки в строках
        title = item_data['title'].replace("'", "''")
        description = item_data['description'].replace("'", "''")
        item_image = item_data['item_image'].replace("'", "''")
        
        # Подготавливаем значения для uses и modifier_turns
        uses = str(item_data['uses']) if item_data['uses'] is not None else 'NULL'
        modifier_turns = str(item_data['modifier_turns']) if item_data['modifier_turns'] is not None else 'NULL'
        
        op.execute(f"""
            INSERT INTO items (title, description, item_image, type, uses, modifier_turns)
            VALUES (
                '{title}',
                '{description}',
                '{item_image}',
                '{item_data['type']}'::itemtype,
                {uses},
                {modifier_turns}
            )
        """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем все данные из таблицы items
    op.execute("DELETE FROM items")
    
    # ### end Alembic commands ###
