"""Populate cells table with game board data

Revision ID: bd7196417521
Revises: 78bdfed4addd
Create Date: 2025-08-23 10:04:04.505011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7196417521'
down_revision: Union[str, None] = '78bdfed4addd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Данные для ячеек игрового поля
    cells_data = [
        {
            'position': 0,
            'title': 'СТАРТ',
            'type': 'START',
            'background_image': 'public/storage/cells/start.png',
            'main_conditions': '{"event": "+ 5 Победных очков"}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 1,
            'title': 'Kalawar (Alawar)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/kalawar.png',
            'main_conditions': '{"duration": "1-4", "price": "0-6"}',
            'genre_conditions': '{"tags": ["Point & Click", "Point-and-click"]}',
            'traps': '{}'
        },
        {
            'position': 2,
            'title': 'Подлянка/Кайфарик 1',
            'type': 'TRAP',
            'background_image': 'public/storage/cells/podlyanka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 3,
            'title': 'THREE-DP (FIVE-BN)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/three-dp.png',
            'main_conditions': '{"duration": "2-5", "price": "5-12"}',
            'genre_conditions': '{"tags": ["Point & Click", "Point-and-click"]}',
            'traps': '{}'
        },
        {
            'position': 4,
            'title': 'YEA GAMES (EA GAMES)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/yea-games.png',
            'main_conditions': '{"duration": "1-5", "price": "7-15"}',
            'genre_conditions': '{"tags": ["FPS", "Shooter"]}',
            'traps': '{}'
        },
        {
            'position': 5,
            'title': 'Вопросик 1',
            'type': 'QUESTION',
            'background_image': 'public/storage/cells/question-cell-ka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 6,
            'title': 'DYDOCE (DICE)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/dydoce.png',
            'main_conditions': '{"duration": "2-7", "price": "0-8"}',
            'genre_conditions': '{"tags": ["FPS", "Shooter"]}',
            'traps': '{}'
        },
        {
            'position': 7,
            'title': 'BIG DISH (BIG FISH)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/big-cock-dish-lmao-----hyyyyyyyyyype.png',
            'main_conditions': '{"duration": "3-7", "price": "0-10"}',
            'genre_conditions': '{"tags": ["Point & Click", "Point-and-click"]}',
            'traps': '{}'
        },
        {
            'position': 8,
            'title': 'Deactivision (Activision)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/deactivisionXXX.png',
            'main_conditions': '{"duration": "3-8", "price": "10-20"}',
            'genre_conditions': '{"tags": ["FPS", "Shooter"]}',
            'traps': '{}'
        },
        {
            'position': 9,
            'title': 'Pornstar Games (Rockstar Games)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/rock.png',
            'main_conditions': '{"duration": "4-10", "price": "15-30"}',
            'genre_conditions': '{"tags": ["FPS", "Shooter"]}',
            'traps': '{}'
        },
        {
            'position': 10,
            'title': 'ТЮРЯГА',
            'type': 'JAIL',
            'background_image': 'public/storage/cells/.png',
            'main_conditions': '{"duration": "6-16"}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 11,
            'title': 'Naughty boy (Naughty dog)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/naughtyboy.png',
            'main_conditions': '{"duration": "3-7", "rating": "40-80"}',
            'genre_conditions': '{"tags": ["Platformer", "3D Platformer"]}',
            'game_conditions': 'MAIN',
            'traps': '{}'
        },
        {
            'position': 12,
            'title': 'Подлянка/Кайфарик 2',
            'type': 'TRAP',
            'background_image': 'public/storage/cells/podlyanka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 13,
            'title': 'PoroSad Studio (SadSquare Studio)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/porosad.png',
            'main_conditions': '{"duration": "4-8", "price": "7-15"}',
            'genre_conditions': '{"tags": ["Psychological Horror", "Survival Horror", "Horror"]}',
            'traps': '{}'
        },
        {
            'position': 14,
            'title': 'SIGA (SEGA)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/siga.png',
            'main_conditions': '{"duration": "4-8", "price": "0-7"}',
            'genre_conditions': '{"price": "10-20", "tags": ["Platformer", "3D Platformer"]}',
            'traps': '{}'
        },
        {
            'position': 15,
            'title': 'Вопросик 2',
            'type': 'QUESTION',
            'background_image': 'public/storage/cells/question-cell-ka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 16,
            'title': 'CUMCOM (CAPCOM)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/cumcom.png',
            'main_conditions': '{"duration": "5-10", "price": "0-15"}',
            'genre_conditions': '{"duration": "4-10", "tags": ["Psychological Horror", "Survival Horror", "Horror"]}',
            'traps': '{}'
        },
        {
            'position': 17,
            'title': 'Team Plum (Team Cherry)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/team-plum.png',
            'main_conditions': '{"duration": "5-10"}',
            'genre_conditions': '{"duration": "5-10", "tags": ["Platformer", "3D Platformer"]}',
            'traps': '{}'
        },
        {
            'position': 18,
            'title': 'Team Vegan (Team Meat)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/green-meat-boy-with-fork.png',
            'main_conditions': '{"duration": "7-15", "price": "15-30"}',
            'genre_conditions': '{"duration": "8-300", "tags": ["Platformer", "3D Platformer"]}',
            'traps': '{}'
        },
        {
            'position': 19,
            'title': 'Red Head (Red Barrels)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/read-heads.png',
            'main_conditions': '{"duration": "7-15", "price": "0-15"}',
            'genre_conditions': '{"duration": "7-300", "tags": ["Psychological Horror", "Survival Horror", "Horror"]}',
            'traps': '{}'
        },
        {
            'position': 20,
            'title': 'Аукошная',
            'type': 'AUCTION',
            'background_image': 'public/storage/cells/auk.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 21,
            'title': 'LEGKO (LEGO)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/legko.png',
            'main_conditions': '{"rating": "45-85", "price": "15-35"}',
            'genre_conditions': '{"tags": ["Puzzle"]}',
            'traps': '{}'
        },
        {
            'position': 22,
            'title': 'Подлянка/Кайфарик 3',
            'type': 'TRAP',
            'background_image': 'public/storage/cells/podlyanka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 23,
            'title': 'Microguy Games (SuperGiant Games)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/microguygames.png',
            'main_conditions': '{"duration": "7-14"}',
            'genre_conditions': '{"tags": ["Rogue-like", "Roguelike"]}',
            'traps': '{}'
        },
        {
            'position': 24,
            'title': 'Noproofs Games (Fireproof Games)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/noproof-games.png',
            'main_conditions': '{"duration": "6-12", "rating": "30-70"}',
            'genre_conditions': '{"duration": "7-14", "tags": ["Puzzle"]}',
            'traps': '{}'
        },
        {
            'position': 25,
            'title': 'Вопросик 3',
            'type': 'QUESTION',
            'background_image': 'public/storage/cells/question-cell-ka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 26,
            'title': 'Bondage Nyamca (Bandai Namco)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/bondage.png',
            'main_conditions': '{"price": "7-20"}',
            'genre_conditions': '{"duration": "8-18", "tags": ["Anime"]}',
            'traps': '{}'
        },
        {
            'position': 27,
            'title': 'Leather club door (Cellar Door Games)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/clubdoor.png',
            'main_conditions': '{"duration": "8-16", "price": "10-30"}',
            'genre_conditions': '{"duration": "8-300", "tags": ["Rogue-like", "Roguelike"]}',
            'traps': '{}'
        },
        {
            'position': 28,
            'title': 'Vlomve (Valve)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/vlomve.png',
            'main_conditions': '{"duration": "9-17", "price": "20-40"}',
            'genre_conditions': '{"duration": "9-300", "tags": ["Puzzle"]}',
            'traps': '{}'
        },
        {
            'position': 29,
            'title': 'Kawaimi (Konami)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/kawaimi.png',
            'main_conditions': '{"duration": "12-20", "price": "10-20"}',
            'genre_conditions': '{"tags": ["Platformer", "3D Platformer"]}',
            'traps': '{}'
        },
        {
            'position': 30,
            'title': 'Лотерея',
            'type': 'LOTTERY',
            'background_image': 'public/storage/cells/topori.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 31,
            'title': 'Besedka (Bethesda)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/besedka.png',
            'main_conditions': '{"duration": "8-14", "rating": "25-65"}',
            'genre_conditions': '{"duration": "10-20", "tags": ["RPG", "Action RPG", "JRPG", "Tactical RPG"]}',
            'traps': '{}'
        },
        {
            'position': 32,
            'title': 'Подлянка/Кайфарик 4',
            'type': 'TRAP',
            'background_image': 'public/storage/cells/podlyanka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 33,
            'title': 'Squidwardix (SquareEnix)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/squidwardix.png',
            'main_conditions': '{"rating": "20-70", "price": "20-100"}',
            'genre_conditions': '{"rating": "20-60", "tags": ["RPG", "Action RPG", "JRPG", "Tactical RPG"]}',
            'traps': '{}'
        },
        {
            'position': 34,
            'title': 'DVD PROJECT BRED (CD PROJECT RED)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/bred.png',
            'main_conditions': '{"duration": "10-18", "price": "10-25"}',
            'genre_conditions': '{"price": "25-100", "tags": ["RPG", "Action RPG", "JRPG", "Tactical RPG"]}',
            'traps': '{}'
        },
        {
            'position': 35,
            'title': 'Вопросик 4',
            'type': 'QUESTION',
            'background_image': 'public/storage/cells/question-cell-ka.png',
            'main_conditions': '{}',
            'genre_conditions': '{}',
            'traps': '{}'
        },
        {
            'position': 36,
            'title': 'Chelic Entertainment (Relic Entertainment)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/chelic.png',
            'main_conditions': '{"duration": "10-20", "price": "0-25"}',
            'genre_conditions': '{"duration": "10-20", "tags": ["Turn-Based Strategy", "Strategy", "Strategy RPG"]}',
            'traps': '{}'
        },
        {
            'position': 37,
            'title': 'Kunisoft (Ubisoft)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/kunisoft.png',
            'main_conditions': '{"duration": "10-20", "price": "25-100"}',
            'genre_conditions': '{"duration": "14-1000", "tags": ["RPG", "Action RPG", "JRPG", "Tactical RPG"]}',
            'traps': '{}'
        },
        {
            'position': 38,
            'title': 'Piratix Games (Firaxis Games)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/piratix.png',
            'main_conditions': '{"price": "30-100"}',
            'genre_conditions': '{"rating": "55-85", "tags": ["Turn-Based Strategy", "Strategy", "Strategy RPG"]}',
            'traps': '{}'
        },
        {
            'position': 39,
            'title': 'Blazerd (Blizzard)',
            'type': 'GAME',
            'background_image': 'public/storage/cells/blazerd.png',
            'main_conditions': '{"duration": "14-300"}',
            'genre_conditions': '{"duration": "16-300", "tags": ["Turn-Based Strategy", "Strategy", "Strategy RPG"]}',
            'traps': '{}'
        }
    ]
    
    # Вставляем данные в таблицу cells
    for cell_data in cells_data:
        op.execute(f"""
            INSERT INTO cells (position, title, type, background_image, main_conditions, genre_conditions, traps)
            VALUES (
                {cell_data['position']},
                '{cell_data['title']}',
                '{cell_data['type']}'::celltype,
                {f"'{cell_data['background_image']}'" if cell_data['background_image'] else 'NULL'},
                '{cell_data['main_conditions']}',
                '{cell_data['genre_conditions']}',
                '{cell_data['traps']}'
            )
        """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем все данные из таблицы cells
    op.execute("DELETE FROM cells")
    
    # ### end Alembic commands ###
